CALL CSVWRITE(
  '/home/isabella/Projetos/ECLIPSE-BANK-V2/analytics/dados/movimentacoes.csv',
  'SELECT u.ID AS USUARIO_ID, u.NOME AS USUARIO_NOME, c.ID AS CONTA_ID, m.TIPO, m.VALOR, m.SALDO_RESULTANTE, m.CRIADA_EM, m.DESCRICAO
   FROM MOVIMENTACOES m
   JOIN CONTAS c ON c.ID = m.CONTA_ID
   LEFT JOIN USUARIOS u ON u.ID = c.USUARIO_ID
   ORDER BY m.CRIADA_EM'
);
