package com.eclipsebank.backend.enums;

public enum TipoMovimentacao {
    DEPOSITO,
    SAQUE,
    TRANSFERENCIA_ENVIADA,
    TRANSFERENCIA_RECEBIDA,
    PIX_ENVIADO,
    PIX_RECEBIDO,
    APLICACAO_INVESTIMENTO,
    RESGATE_INVESTIMENTO,
    PROVENTO_FII,
    APORTE_META_FINANCEIRA,
    RESGATE_META_FINANCEIRA,
    PAGAMENTO_FATURA,
    EMPRESTIMO_LIBERADO,
    PAGAMENTO_PARCELA_EMPRESTIMO
}
